### ISSUE TITLE
Does not support all valid RPM versions

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-service-replace_using_package_version#47]
opensuse-dhcp-server-image fails now because this warning is now an error:

```
[   48s] /usr/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 4.4.2.P1 is an invalid version and will not be supported in a future release
```

**Comment by dcermak** [comment]
Hm, python is not wrong here… What would you recommend to do here? Just fall back to the previous behavior and take anything as a valid version?

**Comment by Vogtinator** [comment]
> Hm, python is not wrong here…

Technically it isn't, because the module is only meant to compare python package versions. It's unsuitable to compare RPM package versions, which can be pretty much anything.

What about using `rpm.labelCompare` instead?
