### ISSUE TITLE
Use the build recipe as default filename

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-service-replace_using_package_version#5]
Currently, the file to do the replacements in has to be specified explicitly in the `_service` configuration.
The name of the file which is being built by OBS is available to buildtime services like this:

```
BUILD_DATA="${BUILD_DIST/.dist/.data}"
. "${BUILD_DATA}"

# The build script renames the recipe (to strip _service:foo:), but doesn't update .data
RECIPEFILE="${RECIPEFILE##*:}"
```

Which would be a sensible default. `obs-service-kiwi_{label,metainfo}_helper` do it that way as well.

**Comment by davidcassany** [comment]
I like the idea
