### ISSUE TITLE
Support capabilities as package name

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/obs-service-replace_using_package_version#6]
Currently, the value given as `package` parameter has to be part of the corresponding `.rpm` file's name. This is not always the case though, especially when a package got renamed (`Provides: foo` + `Obsoletes: foo < %{version}`) or is a capability provided by multiple packages.

This would require either iterating all `.rpm` files in the tree or using `zypper` or `libsolv` by creating a repo and doing a query through them.

**Comment by davidcassany** [comment]
Yes that's a limitation, currently I am not having a good idea about how to solve that, but I'll give some thoughts.

**Comment by mcepl** [comment]
I have the same problem with this `_service` file:

```xml
<services>
	<service mode="buildtime" name="kiwi_metainfo_helper"/>
	<service mode="buildtime" name="replace_using_package_version">
		<param name="file">Dockerfile</param>
		<param name="regex">%PKG_VERSION%</param>
		<param name="parse-version">patch</param>
		<param name="package">python3-fanficfare</param>
	</service>
	<service mode="buildtime" name="docker_label_helper"/>
</services>
```

`python3-fanficfare` is a virtual package provided by (currently) `python311-fanficfare`.
